"""LangGraph subgraph for evidence-grounded narrative enhancement.

The graph deliberately owns only four narrative fields.  All deterministic
prediction fields are copied from the baseline and are never generated by the
model or merged from its response.
"""

from __future__ import annotations

import copy
import inspect
import json
import re
from collections.abc import Mapping, Sequence
from dataclasses import asdict, is_dataclass
from pathlib import Path
from time import perf_counter
from typing import TYPE_CHECKING, Any, TypedDict

try:
    from langgraph.graph import END, START, StateGraph
except ImportError as exc:  # pragma: no cover - exercised only without optional dependency
    raise ImportError(
        "Narrative enhancement requires the optional 'langgraph' dependency."
    ) from exc

if TYPE_CHECKING:
    from src.llm.client import ModelCallResult, OpenAIModelClient


ENHANCED_FIELDS = (
    "detailed_conclusion",
    "causes",
    "treatments",
    "safety_impact",
)
_CONTEXT_KEYS = {
    "text",
    "content",
    "raw_text",
    "source_file",
    "block_index",
    "table_index",
    "row_index",
    "column_index",
    "paragraph_index",
    "metadata",
    "source",
    "snippet",
    "title",
    "score",
    "distance",
}
_ID_KEYS = {"evidence_id", "evidence_ids", "id"}
_NUMBER_RE = re.compile(r"(?<![A-Za-z])\d+(?:\.\d+)?")
_GRADE_RE = re.compile(
    r"(?<![A-Za-z])(?:[A-F](?:级|类)?|[一二三四五六七八九十]+级)(?![A-Za-z])"
)
_PROMPT_PATH = Path(__file__).resolve().parents[2] / "prompts" / "narrative_enhancement.md"
_PROMPT_IDENTITY_KEYS = (
    "sample_id",
    "source_file",
    "source",
    "schema_version",
    "report_id",
    "bridge_id",
    "bridge_name",
    "inspection_id",
    "history",
)
_MAX_DEFECT_DESCRIPTIONS = 3


class NarrativeState(TypedDict, total=False):
    """State passed between the five graph nodes."""

    baseline_prediction: dict[str, Any]
    prompt_baseline: dict[str, Any]
    sample_id: str
    source_file: str
    split: str
    report_facts: Any
    retrieval_results: Any
    generated_sections: dict[str, Any]
    validation_errors: list[str]
    retry_count: int
    enhanced_prediction: dict[str, Any]
    used_fallback: bool
    call_metrics: dict[str, Any]
    max_retries: int
    generation_attempts: int
    generation_errors: list[str]
    validation_passed: bool
    context: dict[str, Any]


def _load_llm_types() -> tuple[type[Any], type[Any]]:
    """Load the shared client types without owning the client implementation."""

    try:
        from src.llm.client import ModelCallResult, OpenAIModelClient
    except ImportError as exc:  # pragma: no cover - the parent worker supplies this module
        raise ImportError(
            "Narrative enhancement requires src.llm.client.OpenAIModelClient "
            "and src.llm.client.ModelCallResult."
        ) from exc
    return OpenAIModelClient, ModelCallResult


def _jsonable(value: Any) -> Any:
    """Convert common project objects to JSON-compatible values."""

    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, Path):
        return str(value)
    if is_dataclass(value):
        return _jsonable(asdict(value))
    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return _jsonable(to_dict())
    model_dump = getattr(value, "model_dump", None)
    if callable(model_dump):
        return _jsonable(model_dump())
    if isinstance(value, Mapping):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
        return [_jsonable(item) for item in value]
    return str(value)


def _prediction_dict(prediction: Any) -> dict[str, Any]:
    normalized = _jsonable(prediction)
    if not isinstance(normalized, dict):
        raise TypeError("baseline_prediction must be a mapping or prediction object")
    return copy.deepcopy(normalized)


def _compact_defects(defects: Any) -> list[dict[str, Any]]:
    """Group repeated defects while retaining a few useful descriptions."""

    if not isinstance(defects, Sequence) or isinstance(defects, (str, bytes, bytearray)):
        return []
    grouped: dict[tuple[str, str], list[str]] = {}
    for defect in defects:
        if not isinstance(defect, Mapping):
            continue
        location = str(defect.get("location") or "").strip()
        defect_type = str(defect.get("defect_type") or "").strip()
        description = str(defect.get("description") or defect.get("text") or "").strip()
        key = (location, defect_type)
        descriptions = grouped.setdefault(key, [])
        if description and description not in descriptions and len(descriptions) < _MAX_DEFECT_DESCRIPTIONS:
            descriptions.append(description)
    return [
        {
            "location": location,
            "defect_type": defect_type,
            "representative_descriptions": descriptions,
        }
        for (location, defect_type), descriptions in grouped.items()
    ]


def _prompt_baseline(
    baseline: Mapping[str, Any],
    *,
    sample_id: str = "",
    source_file: str = "",
) -> dict[str, Any]:
    """Build the bounded baseline representation sent to the generation prompt."""

    prompt: dict[str, Any] = {}
    for key in _PROMPT_IDENTITY_KEYS:
        if key in baseline:
            prompt[key] = copy.deepcopy(baseline[key])
    prompt["sample_id"] = str(sample_id or baseline.get("sample_id", "") or "")
    prompt["source_file"] = str(source_file or baseline.get("source_file", "") or "")
    prompt["summary"] = copy.deepcopy(baseline.get("summary", {}))
    prompt["defects"] = _compact_defects(baseline.get("defects", []))
    prompt["recommendations"] = copy.deepcopy(baseline.get("recommendations", []))
    return prompt


def _json_dump(value: Any) -> str:
    return json.dumps(_jsonable(value), ensure_ascii=False, indent=2, sort_keys=True)


def _empty_metrics() -> dict[str, Any]:
    return {
        "call_count": 0,
        "calls": 0,
        "prompt_tokens": 0,
        "completion_tokens": 0,
        "total_tokens": 0,
        "latency_ms": 0.0,
        "duration_ms": 0.0,
        "model": None,
    }


def _value_from(value: Any, names: Sequence[str]) -> Any:
    if isinstance(value, Mapping):
        for name in names:
            if name in value:
                return value[name]
        return None
    for name in names:
        if hasattr(value, name):
            return getattr(value, name)
    return None


def _record_metrics(metrics: Mapping[str, Any], result: Any, elapsed_ms: float) -> dict[str, Any]:
    updated = dict(metrics)
    calls = int(updated.get("call_count", 0)) + 1
    updated["call_count"] = calls
    updated["calls"] = calls
    duration_ms = _value_from(result, ("duration_ms",))
    if isinstance(duration_ms, (int, float)):
        measured_ms = float(duration_ms)
    else:
        measured_ms = elapsed_ms
    updated["latency_ms"] = round(float(updated.get("latency_ms", 0.0)) + measured_ms, 3)
    updated["duration_ms"] = round(float(updated.get("duration_ms", 0.0)) + measured_ms, 3)

    direct_prompt = _value_from(result, ("prompt_tokens",))
    direct_completion = _value_from(result, ("completion_tokens",))
    direct_total = _value_from(result, ("total_tokens",))
    has_direct_usage = any(
        isinstance(value, (int, float)) for value in (direct_prompt, direct_completion, direct_total)
    )
    if has_direct_usage:
        if isinstance(direct_prompt, (int, float)):
            updated["prompt_tokens"] += int(direct_prompt)
        if isinstance(direct_completion, (int, float)):
            updated["completion_tokens"] += int(direct_completion)
        if isinstance(direct_total, (int, float)):
            updated["total_tokens"] += int(direct_total)
        else:
            updated["total_tokens"] = updated["prompt_tokens"] + updated["completion_tokens"]
    else:
        usage = _value_from(result, ("usage", "token_usage"))
        prompt_tokens = _value_from(usage, ("prompt_tokens", "input_tokens"))
        completion_tokens = _value_from(usage, ("completion_tokens", "output_tokens"))
        total_tokens = _value_from(usage, ("total_tokens",))
        if isinstance(prompt_tokens, (int, float)):
            updated["prompt_tokens"] += int(prompt_tokens)
        if isinstance(completion_tokens, (int, float)):
            updated["completion_tokens"] += int(completion_tokens)
        if isinstance(total_tokens, (int, float)):
            updated["total_tokens"] += int(total_tokens)
        else:
            updated["total_tokens"] = updated["prompt_tokens"] + updated["completion_tokens"]
    model = _value_from(result, ("model",))
    if model is not None:
        updated["model"] = str(model)
    return updated


def _client_call(client: Any, prompt: str) -> Any:
    """Call the shared client while accepting its small public method variants."""

    chat_json = getattr(client, "chat_json", None)
    if callable(chat_json):
        messages = [
            {
                "role": "system",
                "content": "Return only the evidence-grounded narrative JSON requested by the user.",
            },
            {"role": "user", "content": prompt},
        ]
        result = chat_json(messages)
        if inspect.isawaitable(result):
            raise RuntimeError("async model clients are not supported by the sync graph")
        return result

    for method_name in ("generate", "generate_json", "complete", "call", "invoke"):
        method = getattr(client, method_name, None)
        if callable(method):
            result = method(prompt)
            if inspect.isawaitable(result):
                raise RuntimeError("async model clients are not supported by the sync graph")
            return result
    if callable(client):
        result = client(prompt)
        if inspect.isawaitable(result):
            raise RuntimeError("async model clients are not supported by the sync graph")
        return result
    raise TypeError("client does not expose a supported synchronous call method")


def _response_payload(result: Any) -> Any:
    """Extract the response payload from ModelCallResult or a test double."""

    if isinstance(result, Mapping):
        if any(field in result for field in ENHANCED_FIELDS):
            return result
        for key in ("value", "parsed", "json", "output", "content", "text", "message", "response", "raw"):
            if key in result:
                return _response_payload(result[key])
        return result
    if isinstance(result, (str, bytes, bytearray)):
        text = result.decode("utf-8") if isinstance(result, (bytes, bytearray)) else result
        fenced = re.search(r"```(?:json)?\s*(.*?)```", text, flags=re.IGNORECASE | re.DOTALL)
        if fenced:
            text = fenced.group(1).strip()
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            start, end = text.find("{"), text.rfind("}")
            if start < 0 or end <= start:
                raise ValueError("model response is not valid JSON") from None
            try:
                return json.loads(text[start : end + 1])
            except json.JSONDecodeError:
                raise ValueError("model response is not valid JSON") from None

    for name in ("value", "parsed", "json", "output", "content", "text", "message", "response", "raw"):
        value = getattr(result, name, None)
        if value is not None:
            return _response_payload(value)
    raise ValueError("model response did not contain JSON")


def _render_prompt(state: NarrativeState) -> str:
    template = _PROMPT_PATH.read_text(encoding="utf-8")
    prompt_baseline = state.get("prompt_baseline")
    if not isinstance(prompt_baseline, Mapping):
        prompt_baseline = _prompt_baseline(
            state.get("baseline_prediction", {}),
            sample_id=str(state.get("sample_id", "")),
            source_file=str(state.get("source_file", "")),
        )
    replacements = {
        "{{SAMPLE_ID}}": str(state.get("sample_id", "")),
        "{{SOURCE_FILE}}": str(state.get("source_file", "")),
        "{{BASELINE_PREDICTION}}": _json_dump(prompt_baseline),
        "{{REPORT_FACTS}}": _json_dump(state.get("report_facts", [])),
        "{{RETRIEVAL_RESULTS}}": _json_dump(state.get("retrieval_results", [])),
        "{{VALIDATION_ERRORS}}": _json_dump(state.get("validation_errors", [])),
    }
    for marker, replacement in replacements.items():
        template = template.replace(marker, replacement)
    return template


def _query_from_baseline(baseline: Mapping[str, Any]) -> str:
    summary = baseline.get("summary")
    summary_map = summary if isinstance(summary, Mapping) else {}
    pieces = [
        str(summary_map.get("bridge_name", baseline.get("bridge_name", ""))),
        str(summary_map.get("overall_conclusion", "")),
        str(summary_map.get("risk_points", "")),
    ]
    defects = baseline.get("defects", [])
    if isinstance(defects, Sequence) and not isinstance(defects, (str, bytes, bytearray)):
        for defect in defects:
            if isinstance(defect, Mapping):
                pieces.append(" ".join(str(defect.get(key, "")) for key in ("location", "defect_type", "description")))
    return " ".join(piece for piece in pieces if piece).strip()[:2000]


def _prepare_context(state: NarrativeState, max_retries: int) -> dict[str, Any]:
    baseline = _prediction_dict(state.get("baseline_prediction", {}))
    report_facts = _jsonable(state.get("report_facts", []))
    return {
        "baseline_prediction": baseline,
        "prompt_baseline": _prompt_baseline(
            baseline,
            sample_id=str(state.get("sample_id", "")),
            source_file=str(state.get("source_file", "")),
        ),
        "report_facts": report_facts,
        "retrieval_results": [],
        "generated_sections": {},
        "validation_errors": [],
        "retry_count": 0,
        "enhanced_prediction": copy.deepcopy(baseline),
        "used_fallback": False,
        "call_metrics": _empty_metrics(),
        "max_retries": max_retries,
        "generation_attempts": 0,
        "generation_errors": [],
        "validation_passed": False,
        "context": {"query": _query_from_baseline(baseline)},
    }


def _retrieve_knowledge(state: NarrativeState, retriever: Any) -> dict[str, Any]:
    if retriever is None:
        return {"retrieval_results": []}
    query = str(state.get("context", {}).get("query", ""))
    try:
        results = retriever.retrieve(
            query,
            sample_id=state.get("sample_id", ""),
            split=state.get("split", "fit"),
            top_k=5,
        )
    except Exception:
        # Retrieval is optional context.  A retrieval outage must not change the
        # deterministic baseline or leak an external exception into validation.
        results = []
    if results is None:
        results = []
    return {"retrieval_results": _jsonable(results)}


def _generate_narrative(state: NarrativeState, client: Any) -> dict[str, Any]:
    attempts = int(state.get("generation_attempts", 0))
    retry_count = max(0, attempts)
    prompt = _render_prompt(state)
    started = perf_counter()
    try:
        result = _client_call(client, prompt)
    except Exception:
        elapsed_ms = (perf_counter() - started) * 1000
        metrics = _record_metrics(state.get("call_metrics", _empty_metrics()), None, elapsed_ms)
        return {
            "generation_attempts": attempts + 1,
            "retry_count": retry_count,
            "generated_sections": {},
            "generation_errors": ["model call failed"],
            "validation_errors": ["model call failed"],
            "call_metrics": metrics,
        }

    elapsed_ms = (perf_counter() - started) * 1000
    metrics = _record_metrics(state.get("call_metrics", _empty_metrics()), result, elapsed_ms)
    try:
        payload = _response_payload(result)
        if not isinstance(payload, Mapping):
            raise ValueError("model response must be a JSON object")
        generated = _jsonable(payload)
        if not isinstance(generated, dict):
            raise ValueError("model response must be a JSON object")
    except (TypeError, ValueError, json.JSONDecodeError):
        return {
            "generation_attempts": attempts + 1,
            "retry_count": retry_count,
            "generated_sections": {},
            "generation_errors": ["model response is not valid JSON"],
            "validation_errors": ["model response is not valid JSON"],
            "call_metrics": metrics,
        }
    return {
        "generation_attempts": attempts + 1,
        "retry_count": retry_count,
        "generated_sections": generated,
        "generation_errors": [],
        "validation_errors": [],
        "call_metrics": metrics,
    }


def _collect_evidence_ids(value: Any, depth: int = 0) -> set[str]:
    found: set[str] = set()
    if isinstance(value, Mapping):
        for key, item in value.items():
            key_text = str(key)
            if key_text == "evidence_id" or key_text == "id":
                if isinstance(item, (str, int)) and not isinstance(item, bool):
                    found.add(str(item))
            elif key_text == "evidence_ids" and isinstance(item, Sequence) and not isinstance(item, (str, bytes, bytearray)):
                found.update(str(identifier) for identifier in item if isinstance(identifier, (str, int)))
            elif depth == 0 and key_text not in _CONTEXT_KEYS and key_text not in _ID_KEYS:
                # Also support a mapping keyed by stable evidence id.
                found.add(key_text)
            found.update(_collect_evidence_ids(item, depth + 1))
    elif isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
        for item in value:
            found.update(_collect_evidence_ids(item, depth + 1))
    return found


def _baseline_recommendation_count(baseline: Mapping[str, Any]) -> int:
    recommendations = baseline.get("recommendations", [])
    if isinstance(recommendations, Sequence) and not isinstance(recommendations, (str, bytes, bytearray)):
        return len(recommendations)
    return 0


def _candidate_texts(candidate: Mapping[str, Any]) -> list[str]:
    texts: list[str] = []
    detailed = candidate.get("detailed_conclusion", [])
    if isinstance(detailed, list):
        texts.extend(item for item in detailed if isinstance(item, str))
    for field in ("causes", "treatments", "safety_impact"):
        values = candidate.get(field, [])
        if not isinstance(values, list):
            continue
        for item in values:
            if isinstance(item, Mapping) and isinstance(item.get("text"), str):
                texts.append(item["text"])
    return texts


def _context_tokens(value: Any) -> tuple[set[str], set[str]]:
    text = _json_dump(value)
    return set(_NUMBER_RE.findall(text)), set(_GRADE_RE.findall(text))


def _has_locked_change(candidate: Mapping[str, Any], baseline: Mapping[str, Any]) -> bool:
    """Detect explicit attempts to change known locked fields in model JSON."""

    def walk(current: Any, original: Any, at_top: bool = False) -> bool:
        if not isinstance(current, Mapping) or not isinstance(original, Mapping):
            return False
        for key, value in current.items():
            if at_top and key in ENHANCED_FIELDS:
                continue
            if key not in original:
                continue
            original_value = original[key]
            if isinstance(value, Mapping) and isinstance(original_value, Mapping):
                if walk(value, original_value, False):
                    return True
            elif value != original_value:
                return True
        return False

    return walk(candidate, baseline, True)


def _validate_output(state: NarrativeState) -> dict[str, Any]:
    candidate = state.get("generated_sections", {})
    baseline = state.get("baseline_prediction", {})
    errors: list[str] = []

    def add(message: str) -> None:
        if message not in errors:
            errors.append(message)

    for message in state.get("generation_errors", []):
        add(message)
    if not isinstance(candidate, Mapping):
        add("generated sections must be a JSON object")
        return {"validation_errors": errors, "validation_passed": False}

    for field in ENHANCED_FIELDS:
        if field not in candidate:
            add(f"missing generated field: {field}")

    detailed = candidate.get("detailed_conclusion")
    if detailed is not None:
        if not isinstance(detailed, list):
            add("detailed_conclusion must be an array")
        else:
            if len(detailed) > 4:
                add("detailed_conclusion must contain at most four paragraphs")
            if any(not isinstance(item, str) for item in detailed):
                add("detailed_conclusion items must be strings")

    allowed_ids = _collect_evidence_ids(state.get("report_facts", []))
    allowed_ids.update(_collect_evidence_ids(state.get("retrieval_results", [])))
    for field in ("causes", "treatments", "safety_impact"):
        values = candidate.get(field)
        if values is None:
            continue
        if not isinstance(values, list):
            add(f"{field} must be an array")
            continue
        if field == "treatments" and len(values) > _baseline_recommendation_count(baseline):
            add("treatments cannot exceed baseline recommendations")
        required = {"text", "evidence_ids"}
        if field == "treatments":
            required.add("recommendation_index")
        for index, item in enumerate(values):
            if not isinstance(item, Mapping):
                add(f"{field}[{index}] must be an object")
                continue
            if not required.issubset(item):
                add(f"{field}[{index}] is missing a required field")
            if not isinstance(item.get("text"), str):
                add(f"{field}[{index}].text must be a string")
            if field == "treatments" and not isinstance(item.get("recommendation_index"), (str, int)):
                add(f"{field}[{index}].recommendation_index must be a string or integer")
            evidence_ids = item.get("evidence_ids")
            if not isinstance(evidence_ids, list) or any(
                not isinstance(identifier, (str, int)) or isinstance(identifier, bool) for identifier in evidence_ids
            ):
                add(f"{field}[{index}].evidence_ids must be an array of identifiers")
            elif any(str(identifier) not in allowed_ids for identifier in evidence_ids):
                add(f"{field}[{index}] contains an unknown evidence_id")

    if isinstance(baseline, Mapping) and _has_locked_change(candidate, baseline):
        add("generated output attempts to change a locked deterministic field")

    allowed_numbers, allowed_grades = _context_tokens(
        {
            "baseline_prediction": baseline,
            "report_facts": state.get("report_facts", []),
            "retrieval_results": state.get("retrieval_results", []),
        }
    )
    for text in _candidate_texts(candidate):
        if any(token not in allowed_numbers for token in _NUMBER_RE.findall(text)):
            add("generated narrative introduces an unsupported number, grade, or date")
        if any(token not in allowed_grades for token in _GRADE_RE.findall(text)):
            add("generated narrative introduces an unsupported number, grade, or date")

    return {"validation_errors": errors, "validation_passed": not errors}


def _canonical_sections(candidate: Mapping[str, Any]) -> dict[str, Any]:
    canonical: dict[str, Any] = {
        "detailed_conclusion": list(candidate["detailed_conclusion"]),
        "causes": [],
        "treatments": [],
        "safety_impact": [],
    }
    for field in ("causes", "safety_impact"):
        canonical[field] = [
            {"text": item["text"], "evidence_ids": list(item["evidence_ids"])}
            for item in candidate[field]
        ]
    canonical["treatments"] = [
        {
            "recommendation_index": item["recommendation_index"],
            "text": item["text"],
            "evidence_ids": list(item["evidence_ids"]),
        }
        for item in candidate["treatments"]
    ]
    return canonical


def _finalize(state: NarrativeState) -> dict[str, Any]:
    baseline = copy.deepcopy(state.get("baseline_prediction", {}))
    if state.get("validation_passed"):
        candidate = state.get("generated_sections", {})
        enhanced = copy.deepcopy(baseline)
        if isinstance(candidate, Mapping):
            canonical = _canonical_sections(candidate)
            for field in ENHANCED_FIELDS:
                enhanced[field] = canonical[field]
        return {
            "enhanced_prediction": enhanced,
            "generated_sections": _canonical_sections(candidate),
            "used_fallback": False,
            "validation_errors": [],
        }
    return {
        "enhanced_prediction": baseline,
        "used_fallback": True,
        "validation_errors": list(state.get("validation_errors", [])),
    }


def _after_validation(state: NarrativeState) -> str:
    if state.get("validation_passed"):
        return "finalize"
    if int(state.get("retry_count", 0)) < int(state.get("max_retries", 0)):
        return "generate_narrative"
    return "finalize"


def build_narrative_graph(
    client: OpenAIModelClient,
    retriever: Any = None,
    max_retries: int = 1,
):
    """Build and compile the five-node narrative enhancement subgraph."""

    _load_llm_types()
    if max_retries < 0:
        raise ValueError("max_retries must be non-negative")

    graph = StateGraph(NarrativeState)
    graph.add_node("prepare_context", lambda state: _prepare_context(state, max_retries))
    graph.add_node("retrieve_knowledge", lambda state: _retrieve_knowledge(state, retriever))
    graph.add_node("generate_narrative", lambda state: _generate_narrative(state, client))
    graph.add_node("validate_output", _validate_output)
    graph.add_node("finalize", _finalize)
    graph.add_edge(START, "prepare_context")
    graph.add_edge("prepare_context", "retrieve_knowledge")
    graph.add_edge("retrieve_knowledge", "generate_narrative")
    graph.add_edge("generate_narrative", "validate_output")
    graph.add_conditional_edges(
        "validate_output",
        _after_validation,
        {"generate_narrative": "generate_narrative", "finalize": "finalize"},
    )
    graph.add_edge("finalize", END)
    return graph.compile()


def run_narrative_enhancement(
    baseline_prediction: Any,
    sample_id: str,
    source_file: str,
    report_facts: Any,
    client: OpenAIModelClient,
    retriever: Any = None,
    split: str = "fit",
) -> dict[str, Any]:
    """Run narrative enhancement and return the stable public result envelope."""

    graph = build_narrative_graph(client, retriever=retriever, max_retries=1)
    baseline = _prediction_dict(baseline_prediction)
    state: NarrativeState = {
        "baseline_prediction": baseline,
        "prompt_baseline": _prompt_baseline(
            baseline,
            sample_id=sample_id,
            source_file=source_file,
        ),
        "sample_id": sample_id,
        "source_file": source_file,
        "report_facts": report_facts,
        "retrieval_results": [],
        "generated_sections": {},
        "validation_errors": [],
        "retry_count": 0,
        "enhanced_prediction": {},
        "used_fallback": False,
        "call_metrics": _empty_metrics(),
        "split": split,
    }
    result = graph.invoke(state)
    return {
        "enhanced_prediction": result.get("enhanced_prediction", state["baseline_prediction"]),
        "retrieval_results": result.get("retrieval_results", []),
        "generated_sections": result.get("generated_sections", {}),
        "validation_errors": result.get("validation_errors", []),
        "retry_count": result.get("retry_count", 0),
        "used_fallback": result.get("used_fallback", False),
        "call_metrics": result.get("call_metrics", _empty_metrics()),
    }
