"""Stable contracts shared by the Word-first pipeline."""

from .document import (
    DocumentBlock,
    DocumentModel,
    ImageRelation,
    ParagraphBlock,
    TableBlock,
    TableCell,
    TableRow,
)
from .evidence import SourceAnchor
from .prediction import BridgeSummary, DefectObservation, InspectionPrediction, Recommendation
from .semantic_extraction import (
    DecisionStatus,
    DefectRowValidationResult,
    EvidenceSelectionResult,
    ExtractionCandidate,
    FALLBACK_FIELDS_BY_TASK,
    OUTPUT_FIELDS_BY_TASK,
    RECOMMENDATION_CATEGORIES,
    RecommendationCategory,
    RecommendationCategoryResult,
    SEMANTIC_TASK_TYPES,
    SemanticDecision,
    SemanticDecisionResult,
    SemanticExtractionGraphState,
    SemanticTaskType,
    fallback_fields_for,
    validate_decision_for_candidate,
)
from .status import RunStatus, StageStatus

__all__ = [
    "DocumentBlock",
    "DocumentModel",
    "ImageRelation",
    "ParagraphBlock",
    "TableBlock",
    "TableCell",
    "TableRow",
    "InspectionPrediction",
    "BridgeSummary",
    "DefectObservation",
    "Recommendation",
    "RunStatus",
    "SourceAnchor",
    "StageStatus",
    "DecisionStatus",
    "DefectRowValidationResult",
    "EvidenceSelectionResult",
    "ExtractionCandidate",
    "FALLBACK_FIELDS_BY_TASK",
    "OUTPUT_FIELDS_BY_TASK",
    "RECOMMENDATION_CATEGORIES",
    "RecommendationCategory",
    "RecommendationCategoryResult",
    "SEMANTIC_TASK_TYPES",
    "SemanticDecision",
    "SemanticDecisionResult",
    "SemanticExtractionGraphState",
    "SemanticTaskType",
    "fallback_fields_for",
    "validate_decision_for_candidate",
]
